export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAIL = "GET_TODOS_FAIL";
export const RESET_TODOS_COMPONENT = "RESET_TODOS_COMPONENT";
export const TOGGLE_TODO_CHECK = "TOGGLE_TODO_CHECK";
